#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-logs
Version  : 3.32.0
Release  : 10
URL      : https://download.gnome.org/sources/gnome-logs/3.32/gnome-logs-3.32.0.tar.xz
Source0  : https://download.gnome.org/sources/gnome-logs/3.32/gnome-logs-3.32.0.tar.xz
Summary  : A log viewer for the systemd journal
Group    : Development/Tools
License  : GPL-3.0
Requires: gnome-logs-bin = %{version}-%{release}
Requires: gnome-logs-data = %{version}-%{release}
Requires: gnome-logs-license = %{version}-%{release}
Requires: gnome-logs-locales = %{version}-%{release}
BuildRequires : appstream-glib
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : desktop-file-utils
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : glib-dev
BuildRequires : gtk3-dev
BuildRequires : itstool
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gsettings-desktop-schemas)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : sed

%description
GNOME Logs is a log viewer for the systemd journal
https://wiki.gnome.org/Apps/Logs

%package bin
Summary: bin components for the gnome-logs package.
Group: Binaries
Requires: gnome-logs-data = %{version}-%{release}
Requires: gnome-logs-license = %{version}-%{release}

%description bin
bin components for the gnome-logs package.


%package data
Summary: data components for the gnome-logs package.
Group: Data

%description data
data components for the gnome-logs package.


%package doc
Summary: doc components for the gnome-logs package.
Group: Documentation

%description doc
doc components for the gnome-logs package.


%package license
Summary: license components for the gnome-logs package.
Group: Default

%description license
license components for the gnome-logs package.


%package locales
Summary: locales components for the gnome-logs package.
Group: Default

%description locales
locales components for the gnome-logs package.


%prep
%setup -q -n gnome-logs-3.32.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552325235
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1552325235
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-logs
cp COPYING %{buildroot}/usr/share/package-licenses/gnome-logs/COPYING
%make_install
%find_lang gnome-logs

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-logs

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnome.Logs.desktop
/usr/share/dbus-1/services/org.gnome.Logs.service
/usr/share/glib-2.0/schemas/org.gnome.Logs.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.Logs.gschema.xml
/usr/share/icons/hicolor/scalable/apps/org.gnome.Logs.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Logs-symbolic.svg
/usr/share/metainfo/org.gnome.Logs.appdata.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/gnome-logs/index.page
/usr/share/help/C/gnome-logs/introduction.page
/usr/share/help/C/gnome-logs/legal.xml
/usr/share/help/C/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/C/gnome-logs/media/gnome-logs.png
/usr/share/help/C/gnome-logs/permissions.page
/usr/share/help/cs/gnome-logs/index.page
/usr/share/help/cs/gnome-logs/introduction.page
/usr/share/help/cs/gnome-logs/legal.xml
/usr/share/help/cs/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/cs/gnome-logs/media/gnome-logs.png
/usr/share/help/cs/gnome-logs/permissions.page
/usr/share/help/da/gnome-logs/index.page
/usr/share/help/da/gnome-logs/introduction.page
/usr/share/help/da/gnome-logs/legal.xml
/usr/share/help/da/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/da/gnome-logs/media/gnome-logs.png
/usr/share/help/da/gnome-logs/permissions.page
/usr/share/help/de/gnome-logs/index.page
/usr/share/help/de/gnome-logs/introduction.page
/usr/share/help/de/gnome-logs/legal.xml
/usr/share/help/de/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/de/gnome-logs/media/gnome-logs.png
/usr/share/help/de/gnome-logs/permissions.page
/usr/share/help/el/gnome-logs/index.page
/usr/share/help/el/gnome-logs/introduction.page
/usr/share/help/el/gnome-logs/legal.xml
/usr/share/help/el/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/el/gnome-logs/media/gnome-logs.png
/usr/share/help/el/gnome-logs/permissions.page
/usr/share/help/es/gnome-logs/index.page
/usr/share/help/es/gnome-logs/introduction.page
/usr/share/help/es/gnome-logs/legal.xml
/usr/share/help/es/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/es/gnome-logs/media/gnome-logs.png
/usr/share/help/es/gnome-logs/permissions.page
/usr/share/help/fr/gnome-logs/index.page
/usr/share/help/fr/gnome-logs/introduction.page
/usr/share/help/fr/gnome-logs/legal.xml
/usr/share/help/fr/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/fr/gnome-logs/media/gnome-logs.png
/usr/share/help/fr/gnome-logs/permissions.page
/usr/share/help/gl/gnome-logs/index.page
/usr/share/help/gl/gnome-logs/introduction.page
/usr/share/help/gl/gnome-logs/legal.xml
/usr/share/help/gl/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/gl/gnome-logs/media/gnome-logs.png
/usr/share/help/gl/gnome-logs/permissions.page
/usr/share/help/hu/gnome-logs/index.page
/usr/share/help/hu/gnome-logs/introduction.page
/usr/share/help/hu/gnome-logs/legal.xml
/usr/share/help/hu/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/hu/gnome-logs/media/gnome-logs.png
/usr/share/help/hu/gnome-logs/permissions.page
/usr/share/help/ko/gnome-logs/index.page
/usr/share/help/ko/gnome-logs/introduction.page
/usr/share/help/ko/gnome-logs/legal.xml
/usr/share/help/ko/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/ko/gnome-logs/media/gnome-logs.png
/usr/share/help/ko/gnome-logs/permissions.page
/usr/share/help/nl/gnome-logs/index.page
/usr/share/help/nl/gnome-logs/introduction.page
/usr/share/help/nl/gnome-logs/legal.xml
/usr/share/help/nl/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/nl/gnome-logs/media/gnome-logs.png
/usr/share/help/nl/gnome-logs/permissions.page
/usr/share/help/pl/gnome-logs/index.page
/usr/share/help/pl/gnome-logs/introduction.page
/usr/share/help/pl/gnome-logs/legal.xml
/usr/share/help/pl/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/pl/gnome-logs/media/gnome-logs.png
/usr/share/help/pl/gnome-logs/permissions.page
/usr/share/help/pt_BR/gnome-logs/index.page
/usr/share/help/pt_BR/gnome-logs/introduction.page
/usr/share/help/pt_BR/gnome-logs/legal.xml
/usr/share/help/pt_BR/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/pt_BR/gnome-logs/media/gnome-logs.png
/usr/share/help/pt_BR/gnome-logs/permissions.page
/usr/share/help/ru/gnome-logs/index.page
/usr/share/help/ru/gnome-logs/introduction.page
/usr/share/help/ru/gnome-logs/legal.xml
/usr/share/help/ru/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/ru/gnome-logs/media/gnome-logs.png
/usr/share/help/ru/gnome-logs/permissions.page
/usr/share/help/sv/gnome-logs/index.page
/usr/share/help/sv/gnome-logs/introduction.page
/usr/share/help/sv/gnome-logs/legal.xml
/usr/share/help/sv/gnome-logs/media/gnome-logs-3-12.png
/usr/share/help/sv/gnome-logs/media/gnome-logs.png
/usr/share/help/sv/gnome-logs/permissions.page

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-logs/COPYING

%files locales -f gnome-logs.lang
%defattr(-,root,root,-)

